### ISSUE TITLE
Analysis for the single-well titration experiment

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/assaytools#131]
Just opening this as a reminder that we'll likely need to do some updating to analyze the single-well titration experiments, as the plates are in a different format than we're used to. I'm happy to work on this, I'm just not sure where to start!

**Comment by sonyahanson** [comment]
Yeah, @MehtapIsik and I have talked a bit about this, it would essentially require `quickmodel` to be able to read csv files, I believe it would not be too difficult to implement.

**Comment by steven-albanese** [comment]
Since this has been implemented by PR #133 , I'm going to close this!
