### ISSUE TITLE
security alert for pyyaml dependency

### ISSUE THREAD

**Issue by MehtapIsik** [choderalab/assaytools#137]
There is a security alert from GitHub about the pyyaml package.  It seems pyyaml is not used anywhere in Assaytools. Can we remove it from requirements?

![image](https://user-images.githubusercontent.com/8997658/51707279-ce941700-1fee-11e9-9036-d027fbc88e0c.png)

**Comment by sonyahanson** [comment]
Please feel free to make this change on your own.

**Comment by sonyahanson** [comment]
Fixed in #139
