### ISSUE TITLE
Add pint to dependencies in conda/docs

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/assaytools#45]
We need to be sure to mention `pint` as a dependency in conda/docs. This was a problem @Lucelenie had when first installing `assaytools`.

**Comment by jchodera** [comment]
Weird, I don't think we use that.

**Comment by jchodera** [comment]
Even weirder: We `import pint` in a few files, but we _never use it!_.

Can we just get rid of `import pint` instead?  Or do you know that we actually use it somewhere?

**Comment by sonyahanson** [comment]
I don't think I use it anywhere...

**Comment by sonyahanson** [comment]
Yeah... looks fine to delate those.

**Comment by sonyahanson** [comment]
closing.
