### ISSUE TITLE
Make xml2png more general.

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/assaytools#7]
Fix xml2png so it works well for scans and > 3 single reads without manual intervention.

**Comment by jchodera** [comment]
Can you dump some example XML datafiles somewhere, like `examples/xml2png/`?  I'm happy to do this if there are examples to work with!

**Comment by sonyahanson** [comment]
This already existed in xml2png4scans. And I just added the directory xml2png_5, with the 5x extinction coefficient results from last week and the adjusted script I made to look at them.

**Comment by sonyahanson** [comment]
Another thing that is still in progress...
